import streamlit as st
import hmac
from openai import OpenAI
from supabase import create_client
import requests
from datetime import datetime, time
from bs4 import BeautifulSoup
import random
import urllib.parse
from PIL import Image, ImageOps
import io
from streamlit_cropper import st_cropper 

# 1. PAGE CONFIG & THEME
st.set_page_config(page_title="Ghost Dimension AI", page_icon="👻", layout="wide")

# --- CUSTOM CSS (THE "SLICK" LOOK - FIXED PADDING) ---
st.markdown("""
<style>
    /* MAIN BACKGROUND: Void Black */
    .stApp {
        background-color: #050505;
        color: #e0e0e0;
    }
    
    /* HEADERS: Glowing Green */
    h1, h2, h3 {
        color: #00ff41 !important; 
        font-family: 'Helvetica Neue', sans-serif;
        text-shadow: 0 0 10px rgba(0, 255, 65, 0.3);
    }
    
    /* FIX: INPUT LABELS - FORCE BRIGHT WHITE TEXT */
    label, .stTextInput label, .stTextArea label, .stSelectbox label, .stFileUploader label {
        color: #ffffff !important;
        font-weight: 600 !important;
        font-size: 1rem !important;
    }
    
    /* FIX: BORDERED BOXES - AGGRESSIVE PADDING FIX */
    /* This targets the exact container generated by st.container(border=True) */
    div[data-testid="stVerticalBlockBorderWrapper"] {
        padding: 25px !important; /* Forces text away from the edge */
        background-color: #121212;
        border-radius: 12px;
        margin-bottom: 20px;
        border: 1px solid #333; /* Subtle border fallback */
    }

    /* INPUT FIELDS */
    .stTextInput > div > div > input, .stTextArea > div > div > textarea, .stSelectbox > div > div > div {
        background-color: #1c1c1c;
        color: white;
        border: 1px solid #333;
        border-radius: 8px;
    }
    
    /* BUTTONS */
    .stButton > button {
        background-color: transparent;
        color: #00ff41;
        border: 1px solid #00ff41;
        border-radius: 8px;
        transition: all 0.3s ease;
    }
    .stButton > button:hover {
        background-color: #00ff41;
        color: black;
        box-shadow: 0 0 15px rgba(0, 255, 65, 0.7);
    }
    
    /* PRIMARY BUTTONS */
    button[kind="primary"] {
        background-color: #00ff41 !important;
        color: black !important;
        border: none;
        font-weight: bold;
    }
    
    /* TABS */
    .stTabs [data-baseweb="tab-list"] { gap: 10px; }
    .stTabs [data-baseweb="tab"] {
        background-color: #1c1c1c;
        border-radius: 5px;
        color: #888;
    }
    .stTabs [aria-selected="true"] {
        background-color: #00ff41 !important;
        color: black !important;
    }
</style>
""", unsafe_allow_html=True)

# --- SECURITY GATE ---
def check_password():
    def password_entered():
        if hmac.compare_digest(st.session_state["password"], st.secrets["ADMIN_PASSWORD"]):
            st.session_state["password_correct"] = True
            del st.session_state["password"]
        else:
            st.session_state["password_correct"] = False

    if st.session_state.get("password_correct", False): return True
    st.markdown("<h1 style='text-align: center;'>👻 ACCESS RESTRICTED</h1>", unsafe_allow_html=True)
    c1, c2, c3 = st.columns([1,1,1])
    with c2:
        st.text_input("Enter Clearance Code", type="password", on_change=password_entered, key="password")
        if "password_correct" in st.session_state: st.error("🚫 Access Denied")
    return False

if not check_password(): st.stop()

# 2. SETUP
client = OpenAI(api_key=st.secrets["OPENAI_KEY"])
supabase = create_client(st.secrets["SUPABASE_URL"], st.secrets["SUPABASE_KEY"])
MAKE_WEBHOOK_URL = st.secrets["MAKE_WEBHOOK_URL"]

# --- HELPER FUNCTIONS ---
def get_best_time_for_day(target_date):
    day_name = target_date.strftime("%A")
    response = supabase.table("strategy").select("best_hour").eq("day", day_name).execute()
    if response.data: return time(response.data[0]['best_hour'], 0)
    return time(20, 0)

def scrape_website(url):
    if not url.startswith("http"): url = "https://" + url
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
    try:
        page = requests.get(url, headers=headers, timeout=10)
        if page.status_code == 200:
            soup = BeautifulSoup(page.content, "html.parser")
            text = ' '.join([p.text for p in soup.find_all('p')])
            return text[:6000] if len(text) > 50 else None
    except: return None
    return None

def get_brand_knowledge():
    response = supabase.table("brand_knowledge").select("fact_summary").eq("status", "approved").execute()
    if response.data: return "\n".join([f"- {item['fact_summary']}" for item in response.data])
    return "No knowledge yet."

def get_caption_prompt(style, topic_or_desc, context):
    base_prompt = f"Role: Social Media Manager for 'Ghost Dimension'. Context: {context}. Topic: {topic_or_desc}. "
    strategies = {
        "🔥 Viral / Debate (Ask Questions)": "Write a short, punchy caption. The goal is to start a fight in the comments. Ask 'Real or Fake?'. Ask 'What would you do?'. End with a question that forces people to comment.",
        "🕵️ Investigator (Analyze Detail)": "Write a caption that sounds like a paranormal investigator analyzing evidence. Ask the user to zoom in. Ask 'Do you see what I see?'. Focus on a specific scary detail.",
        "📖 Storyteller (Creepypasta)": "Write a 3-sentence mini horror story. Do not be generic. Be atmospheric. End on a cliffhanger that gives chills.",
        "😱 Pure Panic (Short & Scary)": "Write a very short, terrified caption. Use uppercase words for emphasis. Sound like you are currently running away from a ghost. Use emojis like ⚠️👻."
    }
    instruction = strategies.get(style, strategies["🔥 Viral / Debate (Ask Questions)"])
    return f"{base_prompt} \n\nSTRATEGY: {instruction} \n\nMake it sound human, not AI. No cringe hashtags."

# --- MAIN TITLE ---
st.markdown("<h1 style='text-align: center; margin-bottom: 30px;'>👻 GHOST DIMENSION <span style='color: white; font-size: 20px;'>AI SYSTEM</span></h1>", unsafe_allow_html=True)

# 3. CONTENT CREATION AREA
tab_gen, tab_upload = st.tabs(["✨ GENERATE NEW", "📸 EVIDENCE ANALYSIS"])

# --- TAB A: GENERATE FROM SCRATCH ---
with tab_gen:
    with st.container(border=True):
        c_head, c_body = st.columns([1, 2])
        
        # --- LEFT: BRAIN MANAGER ---
        with c_head:
            st.info("🧠 **Knowledge Base**")
            
            # Sub-tabs for URL vs Paste
            learn_t1, learn_t2 = st.tabs(["🔗 Via URL", "📝 Paste Text"])
            
            with learn_t1:
                learn_url = st.text_input("Website URL", label_visibility="visible", placeholder="https://...")
                if st.button("📥 Scrape Site"):
                    with st.spinner("Scraping..."):
                        raw_text = scrape_website(learn_url)
                        if raw_text:
                            prompt = f"Extract 3-5 facts about 'Ghost Dimension' from this:\n{raw_text}"
                            resp = client.chat.completions.create(model="gpt-4", messages=[{"role": "user", "content": prompt}])
                            for fact in resp.choices[0].message.content.split('\n'):
                                clean = fact.strip().replace("- ", "")
                                if len(clean) > 10:
                                    supabase.table("brand_knowledge").insert({"source_url": learn_url, "fact_summary": clean, "status": "pending"}).execute()
                            st.success("Facts Learned! Review below.")
                            st.rerun()
                        else: st.error("Site Blocked. Use 'Paste Text' tab.")

            with learn_t2:
                manual_text = st.text_area("Paste text manually here", height=100)
                if st.button("📥 Learn Text"):
                    with st.spinner("Processing..."):
                        if len(manual_text) > 20:
                            prompt = f"Extract 3-5 facts about 'Ghost Dimension' from this:\n{manual_text}"
                            resp = client.chat.completions.create(model="gpt-4", messages=[{"role": "user", "content": prompt}])
                            for fact in resp.choices[0].message.content.split('\n'):
                                clean = fact.strip().replace("- ", "")
                                if len(clean) > 10:
                                    supabase.table("brand_knowledge").insert({"source_url": "Manual Paste", "fact_summary": clean, "status": "pending"}).execute()
                            st.success("Facts Learned! Review below.")
                            st.rerun()
            
            # --- PENDING FACTS REVIEW SECTION ---
            st.divider()
            st.write("🔍 **Pending Approval**")
            pending_facts = supabase.table("brand_knowledge").select("*").eq("status", "pending").execute().data
            
            if pending_facts:
                for fact in pending_facts:
                    with st.container(border=True):
                        st.caption(f"Source: {fact['source_url']}")
                        st.write(f"_{fact['fact_summary']}_")
                        b1, b2 = st.columns(2)
                        with b1:
                            if st.button("✅ Approve", key=f"app_{fact['id']}"):
                                supabase.table("brand_knowledge").update({"status": "approved"}).eq("id", fact['id']).execute()
                                st.rerun()
                        with b2:
                            if st.button("❌ Reject", key=f"rej_{fact['id']}"):
                                supabase.table("brand_knowledge").delete().eq("id", fact['id']).execute()
                                st.rerun()
            else:
                st.caption("No new facts waiting.")

        # --- RIGHT: GENERATE SECTION ---
        with c_body:
            st.subheader("Create Content")
            topic = st.text_area("What is the subject?", placeholder="e.g. The hanging dolls of Pluckley Village...", height=100)
            
            c1, c2 = st.columns(2)
            with c1:
                style_choice = st.selectbox(
                    "Visual Style",
                    [
                        "🟢 CCTV / Night Vision (Classic)",
                        "🎬 Cinematic Horror (Sharp & Realistic)",
                        "📸 Vintage Photograph (Sepia/Damaged)",
                        "🎄 Christmas / Yule Horror",
                        "🎃 Halloween / Samhain",
                        "❄️ Deep Winter",
                        "☀️ Midsummer Nightmare"
                    ]
                )
            with c2:
                caption_style = st.selectbox(
                    "Caption Strategy",
                    [
                        "🔥 Viral / Debate (Ask Questions)",
                        "🕵️ Investigator (Analyze Detail)",
                        "📖 Storyteller (Creepypasta)",
                        "😱 Pure Panic (Short & Scary)"
                    ]
                )
            
            style_prompts = {
                "🟢 CCTV / Night Vision (Classic)": "Night vision green tint, grainy CCTV security camera footage style, low resolution feel.",
                "🎬 Cinematic Horror (Sharp & Realistic)": "High budget horror movie screenshot, cinematic lighting, 4k resolution, sharp focus, hyperrealistic.",
                "📸 Vintage Photograph (Sepia/Damaged)": "Authentic 1920s spirit photography, sepia tone, dust and scratches, victorian gothic atmosphere.",
                "🎄 Christmas / Yule Horror": "Christmas horror style, twisted holiday decorations, falling snow, Krampus atmosphere.",
                "🎃 Halloween / Samhain": "Classic Halloween horror style, autumn leaves, pumpkin orange palette, thick fog.",
                "❄️ Deep Winter": "Frozen winter horror, ice and frost, breath visible, bleak blue tones.",
                "☀️ Midsummer Nightmare": "Folk horror style, bright daylight, heat haze, Midsommar movie vibes."
            }

            if st.button("🚀 GENERATE DRAFT", type="primary"):
                with st.spinner("Summoning AI Entities..."):
                    try:
                        # 1. Caption
                        knowledge = get_brand_knowledge()
                        final_cap_prompt = get_caption_prompt(caption_style, topic, knowledge)
                        cap_resp = client.chat.completions.create(model="gpt-4", messages=[{"role": "user", "content": final_cap_prompt}])
                        caption = cap_resp.choices[0].message.content
                        
                        # 2. Image
                        selected_style_instruction = style_prompts.get(style_choice, style_prompts["🎬 Cinematic Horror (Sharp & Realistic)"])
                        final_img_prompt = f"A scary paranormal image of {topic}. {selected_style_instruction} Make it look authentic and terrifying."
                        
                        img_resp = client.images.generate(model="dall-e-3", prompt=final_img_prompt, size="1024x1024", quality="hd")
                        image_url = img_resp.data[0].url
                        
                        supabase.table("social_posts").insert({"caption": caption, "image_url": image_url, "topic": topic, "status": "draft"}).execute()
                        st.success("Draft Created!")
                    except Exception as e: st.error(f"Error: {e}")

# --- TAB B: UPLOAD & CROP ---
with tab_upload:
    c1, c2 = st.columns([1, 1])
    
    with c1:
        st.subheader("1. Upload & Crop")
        uploaded_file = st.file_uploader("Choose a photo...", type=['jpg', 'png', 'jpeg'])
        
        if uploaded_file:
            image = Image.open(uploaded_file)
            image = ImageOps.exif_transpose(image)
            st.write("👇 **Drag the box to select your square area:**")
            cropped_img = st_cropper(image, aspect_ratio=(1, 1), box_color='#00ff41', should_resize_image=True)
            st.write("Preview:")
            st.image(cropped_img, width=150)
            
            if st.button("✅ Confirm & Save to Library", type="primary"):
                with st.spinner("Saving..."):
                    try:
                        if cropped_img.mode != "RGB": cropped_img = cropped_img.convert("RGB")
                        final_img = cropped_img.resize((1080, 1080))
                        buf = io.BytesIO()
                        final_img.save(buf, format="JPEG", quality=95)
                        byte_data = buf.getvalue()
                        filename = f"crop_{datetime.now().strftime('%Y%m%d%H%M%S')}.jpg"
                        supabase.storage.from_("uploads").upload(f"evidence_{filename}", byte_data, {"content-type": "image/jpeg"})
                        final_url = supabase.storage.from_("uploads").get_public_url(f"evidence_{filename}")
                        supabase.table("uploaded_images").insert({"file_url": final_url, "filename": filename}).execute()
                        st.success("Saved!"); st.rerun()
                    except Exception as e: st.error(f"Save failed: {e}")

    with c2:
        st.subheader("2. Library & Generate")
        
        upload_caption_style = st.selectbox(
            "Caption Strategy for Evidence:",
            [
                "🔥 Viral / Debate (Ask Questions)",
                "🕵️ Investigator (Analyze Detail)",
                "📖 Storyteller (Creepypasta)",
                "😱 Pure Panic (Short & Scary)"
            ],
            key="upload_cap_style"
        )
        
        st.divider()
        st.write("📂 **Evidence Library (Recent 9)**")
        library = supabase.table("uploaded_images").select("*").order("created_at", desc=True).limit(9).execute().data
        
        if library:
            cols = st.columns(2)
            for idx, img in enumerate(library):
                with cols[idx % 2]:
                    with st.container(border=True):
                        st.image(img['file_url'], use_column_width=True)
                        if st.button("✨ Create Draft", key=f"gen_{img['id']}", type="primary"):
                            with st.spinner("Analyzing..."):
                                try:
                                    raw_url = img['file_url']
                                    knowledge = get_brand_knowledge()
                                    final_cap_prompt = get_caption_prompt(upload_caption_style, "This spooky image", knowledge) + " Describe what is in the image specifically."
                                    response = client.chat.completions.create(model="gpt-4o", messages=[{"role": "user", "content": [{"type": "text", "text": final_cap_prompt}, {"type": "image_url", "image_url": {"url": raw_url}}]}], max_tokens=300)
                                    caption = response.choices[0].message.content
                                    supabase.table("social_posts").insert({"caption": caption, "image_url": raw_url, "topic": "Uploaded Evidence", "status": "draft"}).execute()
                                    st.success("Draft Created!")
                                except Exception as e: st.error(f"Error: {e}")

                        if st.button("🗑️ Delete", key=f"del_{img['id']}"):
                            supabase.table("uploaded_images").delete().eq("id", img['id']).execute(); st.rerun()
        else: st.info("Upload and crop an image on the left to start.")

# 4. DASHBOARD
st.markdown("---")
st.markdown("<h2 style='text-align: center;'>📲 CONTENT DASHBOARD</h2>", unsafe_allow_html=True)
dash_t1, dash_t2, dash_t3 = st.tabs(["📝 DRAFTS", "📅 SCHEDULED", "📜 HISTORY"])

with dash_t1:
    drafts = supabase.table("social_posts").select("*").eq("status", "draft").order("created_at", desc=True).execute().data
    if not drafts: st.info("No drafts pending.")
    for post in drafts:
        with st.container(border=True):
            col1, col2 = st.columns([1, 2])
            with col1:
                if post.get('image_url'): st.image(post['image_url'], use_column_width=True)
            with col2:
                new_cap = st.text_area("Caption", post['caption'], height=150, key=f"cap_{post['id']}")
                d_col, t_col = st.columns(2)
                with d_col: d = st.date_input("Date", key=f"d_{post['id']}")
                suggested = get_best_time_for_day(d)
                with t_col: t = st.time_input(f"Time (Rec: {suggested})", value=suggested, key=f"t_{post['id']}")
                final_time = f"{d} {t}"
                
                b1, b2, b3 = st.columns(3)
                with b1:
                    if st.button("📅 Schedule", key=f"sch_{post['id']}"):
                        supabase.table("social_posts").update({"caption": new_cap, "scheduled_time": final_time, "status": "scheduled"}).eq("id", post['id']).execute(); st.success("Scheduled!"); st.rerun()
                with b2:
                    if st.button("🚀 Post NOW", key=f"now_{post['id']}", type="primary"):
                        if not post.get('image_url'): st.error("No Image!")
                        else:
                            with st.spinner("Posting..."):
                                try:
                                    r = requests.post(MAKE_WEBHOOK_URL, json={"image_url": post['image_url'], "caption": new_cap})
                                    if r.status_code == 200:
                                        supabase.table("social_posts").update({"caption": new_cap, "scheduled_time": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"), "status": "posted"}).eq("id", post['id']).execute(); st.success("Posted!"); st.rerun()
                                    else: st.error(f"Make Error: {r.text}")
                                except Exception as e: st.error(e)
                with b3:
                    if st.button("🗑️", key=f"del_{post['id']}"):
                        supabase.table("social_posts").delete().eq("id", post['id']).execute(); st.rerun()

with dash_t2:
    scheduled = supabase.table("social_posts").select("*").eq("status", "scheduled").order("scheduled_time").execute().data
    if not scheduled: st.info("Nothing scheduled.")
    for post in scheduled:
        with st.container(border=True):
            c1, c2 = st.columns([1, 4])
            with c1: st.image(post['image_url'], width=100)
            with c2:
                st.subheader(f"Due: {post['scheduled_time']} UTC")
                st.text(post['caption'][:100] + "...")
                if st.button("❌ Cancel", key=f"cancel_{post['id']}"):
                    supabase.table("social_posts").update({"status": "draft"}).eq("id", post['id']).execute(); st.rerun()

with dash_t3:
    history = supabase.table("social_posts").select("*").eq("status", "posted").order("scheduled_time", desc=True).limit(20).execute().data
    if not history: st.info("No history yet.")
    for post in history:
        with st.container(border=True):
            c1, c2 = st.columns([1, 4])
            with c1: st.image(post['image_url'], width=100)
            with c2:
                st.write(f"**Posted on:** {post['scheduled_time']}")
                with st.expander("View Caption"): st.write(post['caption'])
